### ISSUE TITLE
Add support and/or documentation for using web3.unity with react-unity-webgl

### ISSUE THREAD

**Issue by Majiick** [ChainSafe/web3.unity#1245]
I am using https://react-unity-webgl.dev/ and it seems that web3.unity is not compatible with this method of loading Unity on the web.

You run into this error:

```
build.loader.js:330 Invoking error handler due to
ReferenceError: web3UnityInstance is not defined
at _Connect (http://xxx:5173/build/build.framework.js:2190:15)
build.framework.js:2190 Uncaught (in promise) ReferenceError: web3UnityInstance is not defined
    at _Connect (build.framework.js:2190:15)
```

Because web3.unity sets `web3UnityInstance` in `index.html`:

```
script.onload = () => {
        createUnityInstance(canvas, config, (progress) => {
          progressBarFull.style.width = 100 * progress + "%";
        }).then((unityInstance) => {
          web3UnityInstance = unityInstance;
          loadingBar.style.display = "none";
          fullscreenButton.onclick = () => {
            unityInstance.SetFullscreen(1);
          };
        }).catch((message) => {
          alert(message);
        });
      };
```

Obviously react-unity-webgl doesn't set that variable.

**Comment by Majiick** [comment]
I figured out how to make it work via this hack:

```
const { unityProvider, sendMessage, isLoaded, loadingProgression } =
		useUnityContext({
			loaderUrl: 'build/build.loader.js',
			dataUrl: 'build/build.data',
			frameworkUrl: 'build/build.framework.js',
			codeUrl: 'build/build.wasm'
		})

...

useEffect(() => {
		window.web3UnityInstance = {
			SendMessage: (gameObjectName, methodName, parameter) => {
				if (!gameObjectName || !methodName) {
					console.error(
						"SendMessage requires at least 'gameObjectName' and 'methodName'."
					)
					return
				}

				// Call the sendMessage function
				sendMessage(gameObjectName, methodName, parameter)

				// Log for debugging
				console.log(
					'SendMessage called with:',
					gameObjectName,
					methodName,
					parameter
				)
			}
		}
	}, [isLoaded])

```

**Comment by kantagara** [comment]
Big thanks @Majiick https://github.com/ChainSafe/game-docs-v2/pull/155 we're updating our docs to reflect your solution (and we've thanked you there 😄 ) and added the general approach to how devs themselves can do it for their own custom webgl templates.
